export const PromotionalOffers = [
    {
      id: 1,
      image: '/promotional-offers/summer-sale.jpg',
      title: 'Summer Sale - 30% OFF!',
      subtitle: 'Book now and save big on your summer getaway.',
      description: 'Enjoy up to 30% off on all bookings made before June 30th. Limited rooms available!',
      price: 'Starting at $99/night',
      discount: '30% Off',
      benefits: ['Complimentary breakfast', 'Free Wi-Fi', 'Early check-in'],
      rules: [
        'Offer valid only for stays during June.',
        'Full payment required at the time of booking.',
      ],
      expirationDate: '2025-06-30',
      category: 'Seasonal Promotions',
    },
    {
      id: 2,
      image: '/promotional-offers/family-package.jpg',
      title: 'Holiday Special – 40% OFF!',
      subtitle: 'Celebrate the holidays with a special discount on your stay.',
      description: 'Get 40% off on all bookings made for the holiday season. Perfect for family get-togethers!',
      price: 'Starting at $129/night',
      discount: '40% Off',
      benefits: ['Family-friendly amenities', 'Free kids’ meals'],
      rules: [
        'Offer applies to bookings for December 15-25.',
        'Cannot be combined with other offers.',
      ],
      expirationDate: '2025-12-25',
      category: 'Holiday Deals',
    },
    {
      id: 3,
      image: '/promotional-offers/early-bird.jpg',
      title: 'Early Bird Discount',
      subtitle: 'Book in advance and get up to 20% off your stay.',
      description: 'Plan your trip ahead and enjoy up to 20% off your room rates when booking 60 days in advance.',
      price: 'Starting at $110/night',
      discount: '20% Off',
      benefits: ['Flexible cancellation policy', 'Special rates for extended stays'],
      rules: [
        'Booking must be made at least 60 days in advance.',
        'Changes to bookings may forfeit the discount.',
      ],
      expirationDate: '2025-02-28',
      category: 'Advance Booking',
    },
  ];
  